import fs from "fs";
import path from "path";

import hre from "hardhat";

async function main() {
  const deployments: Record<string, string> = {};

  const AIModelRegistry = await hre.ethers.getContractFactory("AIModelRegistry");
  const PaymentManager = await hre.ethers.getContractFactory("PaymentManager");
  const ReputationSystem = await hre.ethers.getContractFactory("ReputationSystem");
  const MarketplaceToken = await hre.ethers.getContractFactory("MarketplaceToken");

  // This script expects you to have already deployed. It cannot recover addresses from nowhere.
  // For convenience, you can run it manually after deployment and pass addresses via env.
  // NEXT_PUBLIC_* will be written to frontend config.
  const required = [
    "NEXT_PUBLIC_AI_MODEL_REGISTRY_ADDRESS",
    "NEXT_PUBLIC_PAYMENT_MANAGER_ADDRESS",
    "NEXT_PUBLIC_REPUTATION_SYSTEM_ADDRESS",
    "NEXT_PUBLIC_MARKETPLACE_TOKEN_ADDRESS",
  ];

  for (const key of required) {
    const val = process.env[key];
    if (!val) throw new Error(`Missing ${key} in environment`);
    deployments[key] = val;
  }

  const outPath = path.join(__dirname, "..", "..", "lib", "contracts.ts");

  const frontendContent = `// Auto-generated by contracts/scripts/export-deployment.ts\n// Do not commit secrets; only contract addresses.\n\nexport const CONTRACTS = {\n  AI_MODEL_REGISTRY: '${deployments["NEXT_PUBLIC_AI_MODEL_REGISTRY_ADDRESS"]}',\n  PaymentManager: '${deployments["NEXT_PUBLIC_PAYMENT_MANAGER_ADDRESS"]}',\n  ReputationSystem: '${deployments["NEXT_PUBLIC_REPUTATION_SYSTEM_ADDRESS"]}',\n  MarketplaceToken: '${deployments["NEXT_PUBLIC_MARKETPLACE_TOKEN_ADDRESS"]}',\n} as const;\n`;

  fs.writeFileSync(outPath, frontendContent, "utf-8");
  console.log(`Wrote frontend contract addresses to: ${outPath}`);

  // Touch factories to avoid unused warnings.
  void AIModelRegistry;
  void PaymentManager;
  void ReputationSystem;
  void MarketplaceToken;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});

